apiVersion: v1
kind: Secret
metadata:
  name: agrolink-secrets
  namespace: agrolink-prod
type: Opaque
data:
  # These must be base64 encoded when applied manually, 
  # but GitHub Actions can handle this via `kubectl create secret` command.
  SUPABASE_URL: "" 
  SUPABASE_KEY: ""
  JWT_SECRET: ""
