---
- name: Automate AgroLink Kubernetes Deployment
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure Namespace exists
      command: kubectl create namespace agrolink-prod --dry-run=client -o yaml | kubectl apply -f -

    - name: Apply Backend Deployment and Service
      command: kubectl apply -f ../k8s/backend.yaml
      register: backend_result

    - name: Show Backend Apply Result
      debug:
        var: backend_result.stdout

    - name: Apply Frontend Deployment and Service
      command: kubectl apply -f ../k8s/frontend.yaml
      register: frontend_result

    - name: Show Frontend Apply Result
      debug:
        var: frontend_result.stdout

    - name: Verify all pods in namespace
      command: kubectl get pods -n agrolink-prod
      register: pods_result

    - name: Show Pods
      debug:
        var: pods_result.stdout
